account_id = "44484193795fa8650ad26dd3dcd55a9a"
name = "savai-shakti"
site = {bucket = "./src"}
type = "webpack"
workers_dev = true

# [env.production]
# route = ""
# zone_id = ""
# workers_dot_dev = false

# References:
# https://github.com/signalnerve/i18n-example-workers/blob/master/wrangler.toml
