name = "savai-shakti"
type = "webpack"
workers_dev = true

[site]
bucket = "./src"
entry-point = "workers-site"

# [env.production]
# route = ""
# zone_id = ""
# workers_dot_dev = false

# References:
# https://github.com/signalnerve/i18n-example-workers/blob/master/wrangler.toml
