name = "savai-shakti-foundation"
type = "webpack"
workers_dev = true

[site]
bucket = "./src"
entry-point = "workers-site"

[env.production]
route = "savai-shakti-foundation.pages.dev/*"
workers_dot_dev = false
zone_id = ""

# References:
# https://github.com/signalnerve/i18n-example-workers/blob/master/wrangler.toml
# https://developers.cloudflare.com/workers/cli-wrangler
